---
- name: Enable the EPEL Repo for PIP Install
  yum:
    name: epel-release
    state: latest
  when:
    - ansible_distribution == 'CentOS'
  tags:
    - install_mdm

- name: Upgrade OS
  yum:
    name: '*'
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == 'CentOS'
  tags:
    - install_mdm

- name: "Installing Basic Tools"
  package: pkg={{ item }} state=installed update_cache=yes
  with_items:
  - git
  - vim
  - libaio
  - numactl
  - sysfsutils
  - unzip
  - wget
  - net-tools
  - python3
  - python3-pip
  - binutils
  tags:
    - install_mdm

- name: "Installing Basic Tools"
  package: pkg={{ item }} state=installed update_cache=yes
  with_items:
  - python3-pip
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '7'
  tags:
    - install_mdm
    
- name: "Install Python-pexpect"
  pip:
    name: pexpect
  tags:
    - install_mdm

- name: set timezone to UTC
  timezone:
    name: UTC
    hwclock: UTC
  tags:
    - install_mdm

- name: Get version of CentOS
  shell: cat /etc/redhat-release | awk '{print $4}' | awk -F. '{print $1}'
  register: centos_version
  when:
    - ansible_distribution == 'CentOS'
  tags:
    - install_mdm

- name: Set OS version fact
  set_fact:
    el_version: "{{ centos_version.stdout }}"
  when:
    - ansible_distribution == 'CentOS'
  tags:
    - install_mdm

- name: "Copy RHEL 7 SIO Files"
  copy:
    src: ./files/EMC-ScaleIO-lia-{{ vxflex_version }}.el{{ el_version }}.x86_64.rpm
    dest: /tmp/
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_distribution == 'CentOS'
  tags:
    - install_mdm

- name: "Install SIO LIA"
  yum:
    name: '/tmp/EMC-ScaleIO-lia-{{ vxflex_version }}.el{{ el_version }}.x86_64.rpm'
    state: present
    disable_gpg_check: yes
  when:
    - ansible_distribution == 'CentOS'
  tags:
    - install_mdm

- name: Set odd hosts to MANAGER
  set_fact:
    is_manager: "{% if inventory_hostname in groups['mdm'][::2] %}1{% else %}0{% endif %}"
  tags:
    - install_mdm

- name: "Copy RHEL SIO Files"
  copy:
    src: ./files/EMC-ScaleIO-mdm-{{ vxflex_version }}.el{{ el_version }}.x86_64.rpm
    dest: /tmp/
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_distribution == 'CentOS'
  tags:
    - install_mdm

- name: "Install MDM and set the host to Master"
  yum:
    name: '/tmp/EMC-ScaleIO-mdm-{{ vxflex_version }}.el{{ el_version }}.x86_64.rpm'
    state: present
    disable_gpg_check: yes
  environment:
    MDM_ROLE_IS_MANAGER: "{{ is_manager }}"
  when:
    - ansible_distribution == 'CentOS'
  tags:
    - install_mdm

